export { default as Facebook } from "./Facebook"
export { default as Horizontal } from "./Horizontal"
export { default as Instagram } from "./Instagram"
export { default as LearnEarn } from "./LearnEarn"
export { default as Logo } from "./Logo"
export { default as PayConsultancy } from "./PayConsultancy"
export { default as Time } from "./Time"
export { default as Worldwide } from "./Worldwide"
