packages:
    - 'libs/**'
    - 'apps/**'
    - '!apps/legacy_**'

# Define a catalog of version ranges.
catalog:
  "@rsbuild/core": 1.2.4
  "@rsbuild/plugin-react": 1.1.0
  "@rsbuild/plugin-node-polyfill": 1.3.0
  tailwindcss: 4.0.5
  "@tailwindcss/postcss": 4.0.5
  tailwindcss-animate: 1.0.7
  tailwind-merge: 2.6.0
  typescript: 5.7.3
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.12
  "@types/react-dom": 18.3.1
