packages:
    - 'libs/**'
    - 'apps/**'
    - '!apps/legacy_**'

# Define a catalog of version ranges.
catalog:
  "@rsbuild/core": 1.2.15
  "@rsbuild/plugin-react": 1.1.1
  "@rsbuild/plugin-node-polyfill": 1.3.0
  tailwindcss: 4.0.12
  "@tailwindcss/postcss": 4.0.12
  tailwindcss-animate: 1.0.7
  tailwind-merge: 3.0.2
  typescript: 5.8.2
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.12
  "@types/react-dom": 18.3.5
