import '@nmit-coursition/ui/utils/global.css'
import { TRPCReactProvider } from '../trpc/react'

export const metadata = {
  title: 'Welcome to nmit',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='overflow-hidden'>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
