import '@nmit-coursition/ui/utils/global.css'
import { getServerSession } from 'next-auth'
import { SessionProvider } from '../components/session-provider'

export const metadata = {
  title: 'Welcome to nmit',
  description: 'Generated by create-nx-workspace',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession()

  return (
    <html lang='en'>
      <SessionProvider session={session}>
        <body className='overflow-hidden'>{children}</body>
      </SessionProvider>
    </html>
  )
}
